-- PRODUTO_INVESTIMENTO
INSERT INTO produto_investimento (nome, tipo, rentabilidade, risco, created_at, updated_at, uuid)
VALUES
('CDB Banco XP', 'CDB', 0.0480, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('CDB Banco Itau', 'CDB', 0.0320, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('CDB Banco Bradesco', 'CDB', 0.0455, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('LCI Imobiliária', 'LCI', 0.0460, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('LCA Agronegócio', 'LCA', 0.0110, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('Debênture Infraestrutura', 'DEBENTURE', 0.0550, 'MEDIO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('ETF BOVA11', 'ETF', 0.1020, 'ALTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('Bitcoin', 'CRIPTOMOEDA', 0.2500, 'MUITO_ALTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('Poupança Caixa', 'POUPANCA', 0.0300, 'BAIXO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID());

-- PERFIL_INVESTIDOR
INSERT INTO perfil_investidor (titulo, pontuacao, created_at, updated_at, uuid)
VALUES
('CONSERVADOR', 10.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('MODERADO', 57.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('AGRESSIVO', 83.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID());

-- INVESTIDOR
INSERT INTO investidor (nome, created_at, updated_at, uuid, perfil_id)
VALUES
('João Silva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID(), 1),
('Maria Souza', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID(), 2);

INSERT INTO investidor (nome, created_at, updated_at, uuid)
VALUES
('Marcelo Vitório', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID());

-- INVESTIMENTO
INSERT INTO investimento (titulo, tipo, valor_aplicado, prazo_meses, rentabilidade, data_aplicacao, created_at, updated_at, uuid, investidor_id, risco)
VALUES
('CDB Banco XP', 'CDB', 1500.00, 18, 0.0480, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID(), 1, 'BAIXO'),
('ETF BOVA11', 'ETF', 4000.00, 48, 0.1020, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID(), 1, 'ALTO'),
('Bitcoin', 'CRIPTOMOEDA', 5000.00, 12, 0.2500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID(), 1, 'MUITO_ALTO');

INSERT INTO simulacao (produto, valor_investido, valor_final, prazo_meses, data_simulacao, investidor_id, created_at, updated_at, uuid)
VALUES
('CDB Banco XP', 1000.00, 1100.00, 12, CURRENT_DATE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('LCI Imobiliária', 2000.00, 2150.00, 24, CURRENT_DATE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('LCA Agronegócio', 1500.00, 1605.00, 18, CURRENT_DATE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('Tesouro Selic 2025', 3000.00, 3150.00, 36, CURRENT_DATE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID()),
('Bitcoin', 2500.00, 4000.00, 12, CURRENT_DATE, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID());

INSERT INTO telemetry_metrics (endpoint, tempo_resposta, data_coleta, created_at, updated_at, uuid)
VALUES ('/api/test', 123.45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, RANDOM_UUID());

